package: file_importer
version: '1.0.0'
author: KLXM
supportpage: https://github.com/klxm/file_importer

requires:
    redaxo: '^5.18.0'
    php:
        version: '>=8.2'

page:
    title: 'translate:file_importer_title'
    perm: admin[]
    icon: rex-icon fa-cloud-download
    subpages:
        main: 
            title: 'translate:file_importer_images'
        providers:
            title: 'translate:file_importer_providers'
        config:
            title: 'translate:file_importer_settings'

cache:
    fileimporter.search: 
        expiration: 86400  # 24 Stunden Cache für Suchergebnisse
